In [1]:
import sklearn as sk
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
import mglearn
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
# Loading the dataset
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [3]:
# Let us split the data into trainging and testing data.
# In this case X stands for feature data and y is for target data (classes).

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=5)

In [4]:
# Rows, Columns in training feature data
x_train.shape

(112, 4)

In [5]:
# Rows, Columns in training target data

y_train.shape

(112,)

In [6]:
# Using the KNN algorithm for the machine learning model
# the Fit function makes the model learn from the training data

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train) 

KNeighborsClassifier(n_neighbors=3)

In [7]:
# The original target data for testing.
# This is what the predictions should have been
y_test

array([1, 2, 2, 0, 2, 1, 0, 1, 0, 1, 1, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 0, 2])

In [8]:
# Prediction on new data: 

In [9]:

y_pred = knn.predict(x_test)
y_pred

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 2, 2, 0, 2, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 2, 1, 2, 1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 0, 2])

In [12]:
# Accuracy Score:

knn.score(x_test, y_test)

# Looks pretty good!

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9473684210526315

In [11]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, y_pred)
confusion


array([[12,  0,  0],
       [ 0, 12,  2],
       [ 0,  0, 12]], dtype=int64)